import Image from "next/image";
import Link from "next/link";
import { ArrowRight, GraduationCap, Plane, Compass } from "lucide-react";
import { fallbackServices, fallbackEvents } from "@/lib/content";
import { EditorialCta } from "@/components/editorial-cta";

const icons = [GraduationCap, Plane, Compass];
const steps = [["01", "Listen first", "We begin with your academic record, ambitions and practical realities."], ["02", "Map the route", "Together, we shape a destination, course and application strategy."], ["03", "Move with confidence", "You receive clear support through application, visa and departure."]];

export default function Home() {
  return <>
    <section className="home-hero"><div className="shell home-hero__content"><p className="eyebrow" style={{ color: "#fec65e" }}>International education & visa consultancy</p><h1 className="display">A considered route to your global education.</h1><p>From the first possibility to a confident departure, Empire offers clear, personal guidance for students and families across East Africa.</p><div className="home-hero__actions"><Link href="/contact" className="button button-primary">Get in touch <ArrowRight size={18} aria-hidden="true" /></Link><Link href="/countries" className="button button-light">Explore destinations</Link></div></div></section>
    <section className="section shell"><div className="section-heading"><p className="eyebrow">The Empire approach</p><h2 className="heading">Expertise for every decision that matters.</h2><hr className="editorial-rule" /><p className="lead">A focused team, a clear process, and advice shaped around the future you want to build.</p></div><div className="grid grid-3 home-services">{fallbackServices.map((item, index) => { const Icon = icons[index]; return <article key={item.id}><Icon size={24} strokeWidth={1.5} aria-hidden="true" /><p className="eyebrow">0{index + 1}</p><h3 className="heading">{item.title}</h3><p className="prose">{item.description}</p><Link href={`/apply?service=${encodeURIComponent(item.title)}`}>Explore this service <span aria-hidden="true">→</span></Link></article>; })}</div></section>
    <section className="section home-process"><div className="shell grid grid-2" style={{ alignItems: "center" }}><div className="home-process__image"><Image src="https://images.unsplash.com/photo-1529390079861-591de354faf5?auto=format&fit=crop&w=1200&q=80" alt="An adviser in conversation with a student" fill sizes="(max-width: 800px) 100vw, 50vw" style={{ objectFit: "cover" }} /></div><div><p className="eyebrow">From ambition to arrival</p><h2 className="heading">A journey made clear, step by step.</h2><div className="home-steps">{steps.map(([number, title, description]) => <div key={number}><b>{number}</b><div><h3>{title}</h3><p>{description}</p></div></div>)}</div><Link href="/study-abroad" className="text-link">See how we guide your journey <span aria-hidden="true">→</span></Link></div></div></section>
    <section className="section shell"><div className="home-events-heading"><div className="section-heading"><p className="eyebrow">In conversation</p><h2 className="heading">Meet your future, with context.</h2></div><Link className="button button-outline" href="/events">View all events</Link></div><div className="grid grid-2">{fallbackEvents.map((event) => <article className="card home-event" key={event.id}><Image src={event.image_url!} alt="" width={800} height={420} style={{ width: "100%", height: 230, objectFit: "cover" }} /><div><p className="eyebrow">{new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(event.event_date))} · {event.location}</p><h3 className="heading">{event.title}</h3><p className="prose">{event.description}</p><Link href={`/events/${event.slug}`} className="text-link">View event details <span aria-hidden="true">→</span></Link></div></article>)}</div></section>
    <EditorialCta title="Your next chapter deserves a clear beginning.">Book a focused conversation with an Empire adviser and leave with a better sense of what comes next.</EditorialCta>
  </>;
}
