import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Compass, GraduationCap, Plane } from "lucide-react";
import { EditorialCta } from "@/components/editorial-cta";
import { ScrollReveal } from "@/components/scroll-reveal";
import { fallbackEvents, fallbackServices } from "@/lib/content";

const icons = [GraduationCap, Plane, Compass];
const steps = [["01", "Start with what matters", "We listen to your ambitions, academic story and practical considerations before proposing a route."], ["02", "Build a considered plan", "Together, we shape a shortlist, application strategy and timeline you can act on with confidence."], ["03", "Move forward well prepared", "From applications through visa preparation, every next step is clear and supported."]];

export default function Home() {
  return <>
    <section className="signature-hero"><div className="shell signature-hero__grid"><div className="signature-hero__copy"><p className="eyebrow">Empire consultants · East Africa</p><h1 className="display">The world is wide.<br />Your path can be clear.</h1><p>Personal, considered guidance for students and families shaping an international education journey.</p><div className="signature-hero__actions"><Link href="/contact" className="button button-primary">Get in touch <ArrowRight size={18} aria-hidden="true" /></Link><Link href="/countries" className="text-link signature-hero__secondary">Explore destinations <span aria-hidden="true">→</span></Link></div></div><div className="signature-hero__visual"><div className="signature-hero__image"><Image src="https://images.unsplash.com/photo-1529390079861-591de354faf5?auto=format&fit=crop&w=1200&q=85" alt="An Empire adviser in conversation with a student" fill priority sizes="(max-width: 800px) 100vw, 46vw" style={{ objectFit: "cover" }} /></div><p className="signature-hero__note"><span>01</span> A considered beginning</p></div></div></section>
    <section className="section shell home-introduction"><ScrollReveal><div className="home-introduction__statement"><p className="eyebrow">What Empire brings</p><h2 className="heading">More than a destination. A direction that fits the life you want to build.</h2></div></ScrollReveal><div className="home-introduction__detail"><hr className="editorial-rule" /><p className="lead">International education asks for more than an application. It asks for judgement, timing and someone who can make the complex feel navigable.</p><Link href="/about" className="text-link">Meet Empire <span aria-hidden="true">→</span></Link></div></section>
    <section className="section home-offering"><div className="shell"><ScrollReveal><div className="home-offering__heading"><p className="eyebrow">The Empire practice</p><h2 className="heading">One clear partner, across the decisions that shape your next chapter.</h2></div></ScrollReveal><div className="home-offering__list">{fallbackServices.map((service, index) => { const Icon = icons[index]; return <article key={service.id} className="home-service"><p className="home-service__number">0{index + 1}</p><Icon size={22} strokeWidth={1.5} aria-hidden="true" /><div><h3 className="heading">{service.title}</h3><p className="prose">{service.description}</p></div><Link href={`/apply?service=${encodeURIComponent(service.title)}`} className="text-link">Explore <span aria-hidden="true">→</span></Link></article>; })}</div></div></section>
    <section className="section home-journey"><div className="shell home-journey__grid"><div className="home-journey__image"><Image src="https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=80" alt="Students sharing a moment together" fill sizes="(max-width: 800px) 100vw, 50vw" style={{ objectFit: "cover" }} /></div><ScrollReveal className="home-journey__copy"><p className="eyebrow">From ambition to arrival</p><h2 className="heading">A process with room to think, and a plan to move.</h2><div className="home-steps">{steps.map(([number, title, description]) => <div key={number}><b>{number}</b><div><h3>{title}</h3><p>{description}</p></div></div>)}</div><Link href="/study-abroad" className="text-link">See how we guide your journey <span aria-hidden="true">→</span></Link></ScrollReveal></div></section>
    <section className="section shell home-trust"><ScrollReveal><div className="home-trust__lead"><p className="eyebrow">A relationship, not a transaction</p><h2 className="heading">Guidance that respects the weight of the decision.</h2><p className="lead">Families entrust us with an important turning point. We meet it with care, integrity and clear thinking from the first conversation.</p><Link href="/testimonials" className="text-link">Read student stories <span aria-hidden="true">→</span></Link></div></ScrollReveal><div className="home-trust__principles" aria-label="Empire principles"><p><span>Clarity</span> Honest guidance for choices that matter.</p><p><span>Care</span> Personal support throughout the process.</p><p><span>Perspective</span> A global outlook grounded in local understanding.</p></div></section>
    <section className="section home-events"><div className="shell"><div className="home-events__heading"><div><p className="eyebrow">In conversation</p><h2 className="heading">Meet your future, with context.</h2></div><Link href="/events" className="text-link">View all events <span aria-hidden="true">→</span></Link></div><div className="grid grid-2">{fallbackEvents.map((event) => <article className="card home-event" key={event.id}><Image src={event.image_url!} alt="" width={800} height={420} style={{ width: "100%", height: 250, objectFit: "cover" }} /><div><p className="eyebrow">{new Intl.DateTimeFormat("en", { dateStyle: "medium" }).format(new Date(event.event_date))} · {event.location}</p><h3 className="heading">{event.title}</h3><p className="prose">{event.description}</p><Link href={`/events/${event.slug}`} className="text-link">View event details <span aria-hidden="true">→</span></Link></div></article>)}</div></div></section>
    <EditorialCta eyebrow="A conversation worth having" title="A global future begins with one clear conversation.">Tell us where you are now, and together we will identify a more confident next step.</EditorialCta>
  </>;
}
