"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { Edit3, Plus, Trash2, X } from "lucide-react";

type Kind = "services" | "events" | "leads";
type RecordItem = Record<string, unknown>;
const initial = (kind: "services" | "events") => kind === "services" ? { title: "", description: "", display_order: 0, status: "draft", image_url: "" } : { title: "", slug: "", event_date: "", event_time: "", location: "", description: "", featured: false, status: "draft", image_url: "" };

export function AdminCollection({ kind }: { kind: Kind }) {
  const [items, setItems] = useState<RecordItem[]>([]); const [error, setError] = useState(""); const [editing, setEditing] = useState<RecordItem | null>(null); const [source, setSource] = useState(""); const [status, setStatus] = useState("");
  const load = useCallback(async () => { try { const query = kind === "leads" ? `?${new URLSearchParams(Object.entries({ source, status }).filter(([, value]) => value))}` : ""; const response = await fetch(`/api/admin/${kind}${query}`); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Could not load records."); setItems(data); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not load records."); } }, [kind, source, status]);
  useEffect(() => { void load(); }, [load]);
  async function remove(id: string) { if (!confirm("Delete this item? This cannot be undone.")) return; const response = await fetch(`/api/admin/${kind}/${id}`, { method: "DELETE" }); if (!response.ok) { setError("Delete failed."); return; } void load(); }
  async function leadStatus(id: string, value: string) { const response = await fetch(`/api/admin/leads/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: value }) }); if (!response.ok) { setError("Could not update lead."); return; } void load(); }
  return <section style={{ marginTop: 32 }}><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 16, marginBottom: 20 }}>{kind === "leads" ? <div className="admin-filters"><select value={source} aria-label="Filter lead type" onChange={(event) => setSource(event.target.value)}><option value="">All forms</option><option value="inquiry">Inquiry</option><option value="appointment">Appointment</option><option value="event_registration">Event registration</option><option value="contact">Contact</option></select><select value={status} aria-label="Filter lead status" onChange={(event) => setStatus(event.target.value)}><option value="">All statuses</option><option value="new">New</option><option value="contacted">Contacted</option><option value="closed">Closed</option></select></div> : <button className="button button-primary" onClick={() => setEditing(initial(kind))}><Plus size={18} /> Add {kind === "services" ? "service" : "event"}</button>}</div>{error && <p role="alert" style={{ color: "#ba1a1a" }}>{error}</p>}<div className="card" style={{ overflowX: "auto" }}><table className="admin-table"><thead><tr>{(kind === "leads" ? ["Name", "Email", "Source", "Status", "Received", "Detail"] : ["Title", kind === "events" ? "Date" : "Order", "Status", "Updated", "Actions"]).map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{items.map((item) => <tr key={String(item.id)}>{kind === "leads" ? <><td>{String(item.name)}</td><td>{String(item.email)}</td><td>{String(item.source).replace("_", " ")}</td><td><select value={String(item.status)} onChange={(event) => void leadStatus(String(item.id), event.target.value)} aria-label={`Status for ${String(item.name)}`}><option value="new">New</option><option value="contacted">Contacted</option><option value="closed">Closed</option></select></td><td>{new Date(String(item.submitted_at)).toLocaleDateString()}</td><td><details><summary>View</summary><p>{String(item.message || "No message provided.")}</p></details></td></> : <><td><strong>{String(item.title)}</strong></td><td>{kind === "events" ? String(item.event_date) : String(item.display_order)}</td><td>{String(item.status)}</td><td>{new Date(String(item.updated_at)).toLocaleDateString()}</td><td className="admin-actions"><button aria-label={`Edit ${String(item.title)}`} onClick={() => setEditing(item)}><Edit3 size={16} /></button><button aria-label={`Delete ${String(item.title)}`} onClick={() => void remove(String(item.id))}><Trash2 size={16} /></button></td></>}</tr>)}</tbody></table>{!items.length && <p style={{ padding: 16 }}>No records found.</p>}</div>{editing && kind !== "leads" && <Editor kind={kind} item={editing} close={() => setEditing(null)} saved={load} />}</section>;
}

function Editor({ kind, item, close, saved }: { kind: "services" | "events"; item: RecordItem; close: () => void; saved: () => Promise<void> }) {
  const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [image, setImage] = useState(String(item.image_url || ""));
  async function upload(file: File) { const form = new FormData(); form.append("file", file); const response = await fetch("/api/admin/uploads", { method: "POST", body: form }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Image upload failed."); setImage(data.url); }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSaving(true); setError(""); const form = new FormData(event.currentTarget); const payload = kind === "services" ? { title: form.get("title"), description: form.get("description"), display_order: Number(form.get("display_order")), status: form.get("status"), image_url: image || null } : { title: form.get("title"), slug: form.get("slug"), event_date: form.get("event_date"), event_time: form.get("event_time") || null, location: form.get("location"), description: form.get("description"), featured: form.get("featured") === "on", status: form.get("status"), image_url: image || null }; try { const response = await fetch(`/api/admin/${kind}${item.id ? `/${item.id}` : ""}`, { method: item.id ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Save failed."); await saved(); close(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Save failed."); } finally { setSaving(false); } }
  return <div className="admin-modal" role="dialog" aria-modal="true"><form className="card admin-editor" onSubmit={submit}><div style={{ display: "flex", justifyContent: "space-between" }}><h2 className="heading" style={{ fontSize: "1.8rem" }}>{item.id ? "Edit" : "Add"} {kind === "events" ? "event" : "service"}</h2><button type="button" aria-label="Close editor" onClick={close}><X /></button></div><label className="field">Title<input name="title" defaultValue={String(item.title || "")} required /></label>{kind === "events" && <><label className="field">URL slug<input name="slug" defaultValue={String(item.slug || "")} pattern="[a-z0-9-]+" required /></label><div className="grid grid-2"><label className="field">Date<input name="event_date" type="date" defaultValue={String(item.event_date || "")} required /></label><label className="field">Time<input name="event_time" defaultValue={String(item.event_time || "")} /></label></div><label className="field">Location<input name="location" defaultValue={String(item.location || "")} required /></label></>}<label className="field">Description<textarea name="description" defaultValue={String(item.description || "")} required /></label>{kind === "services" && <label className="field">Display order<input name="display_order" type="number" min="0" defaultValue={String(item.display_order || 0)} required /></label>}<label className="field">Image<input type="file" accept="image/*" onChange={async (event) => { const file = event.target.files?.[0]; if (!file) return; try { await upload(file); } catch (reason) { setError(reason instanceof Error ? reason.message : "Upload failed."); } }} /><small>{image ? "Image uploaded and ready to save." : "Optional — uploads are optimized to WebP."}</small></label>{kind === "events" && <label><input name="featured" type="checkbox" defaultChecked={Boolean(item.featured)} /> Feature this event</label>}<label className="field">Status<select name="status" defaultValue={String(item.status || "draft")}><option value="draft">Draft</option><option value="published">Published</option></select></label>{error && <p role="alert" style={{ color: "#ba1a1a" }}>{error}</p>}<button className="button button-primary" disabled={saving}>{saving ? "Saving…" : "Save changes"}</button></form></div>;
}
