create type public.publish_status as enum ('draft', 'published');
create type public.lead_status as enum ('new', 'contacted', 'closed');
create type public.lead_source as enum ('inquiry', 'appointment', 'event_registration', 'contact');
create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, is_admin boolean not null default false, created_at timestamptz not null default now());
create table public.services (id uuid primary key default gen_random_uuid(), title text not null, description text not null, image_url text, display_order integer not null default 0, status public.publish_status not null default 'draft', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.events (id uuid primary key default gen_random_uuid(), slug text not null unique, title text not null, event_date date not null, event_time text, location text not null, description text not null, image_url text, featured boolean not null default false, status public.publish_status not null default 'draft', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.leads (id uuid primary key default gen_random_uuid(), name text not null, email text not null, phone text, message text, source public.lead_source not null, event_id uuid references public.events(id) on delete set null, status public.lead_status not null default 'new', submitted_at timestamptz not null default now());
alter table public.profiles enable row level security; alter table public.services enable row level security; alter table public.events enable row level security; alter table public.leads enable row level security;
create policy "published services public read" on public.services for select using (status = 'published');
create policy "published events public read" on public.events for select using (status = 'published');
create policy "admins manage profiles" on public.profiles for all using ((select is_admin from public.profiles where id = auth.uid()));
create policy "admins manage services" on public.services for all using ((select is_admin from public.profiles where id = auth.uid()));
create policy "admins manage events" on public.events for all using ((select is_admin from public.profiles where id = auth.uid()));
create policy "admins manage leads" on public.leads for all using ((select is_admin from public.profiles where id = auth.uid()));
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;
create trigger services_updated_at before update on public.services for each row execute function public.set_updated_at();
create trigger events_updated_at before update on public.events for each row execute function public.set_updated_at();
insert into storage.buckets (id, name, public) values ('cms-images', 'cms-images', true);
create policy "admin image uploads" on storage.objects for all using (bucket_id = 'cms-images' and (select is_admin from public.profiles where id = auth.uid()));
